<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Invoice;
// Check Model name here and in foreach  method before run seeders!!!

class InvoicesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $invoices = [
            [
                'supplier_id' => 1,
                'client_id' => 1,
                'number' => 1, // not sure about this one, but probably will be autogenerated?
                'additional_notes' => '',
                'status' => 'new',
                'total_amount' => 12500,
                'currency' => 'CZK',
                'formOfPayment' => 'cash',
                'issued_on' => '2022-06-22 17:25:58',
                'due_date' => '2022-06-30 00:00:00'

            ]
        ];
        foreach ($invoices as $invoice) {
            Invoice::create($invoice);
        }
    }
}
